### ISSUE TITLE
package-lock.json is old

### ISSUE THREAD

**Issue by wand2016** [goto-lab/pufu-editor#25]
**Describe the issue**

- The `version` field of the package.json is `0.9.8`, whereas as of package-lock.json is `0.9.2`.
- Found 23 vulnerabilities.

**To Reproduce**

1. clone the repo
2. `npm install`

```
added 1454 packages, and audited 1455 packages in 38s

280 packages are looking for funding
  run `npm fund` for details

23 vulnerabilities (3 low, 8 moderate, 12 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```

3. `git diff`

```diff
--- a/package-lock.json
+++ b/package-lock.json
@@ -1,12 +1,12 @@
 {
   "name": "@goto-lab/pufu-editor",
-  "version": "0.9.2",
+  "version": "0.9.8",
...
```

**Expected behavior**

- `found 0 vulnerabilities`
- no version diff

**Screenshots**

![image](https://github.com/user-attachments/assets/adcf2656-98e9-44fb-9050-1018e8942df2)

![image](https://github.com/user-attachments/assets/adbb6c33-04c9-49de-91b9-c7e8265f0b4d)

**Desktop (please complete the following information):**

- Windows 11 (WSLg)

**Smartphone (please complete the following information):**

N/A

**Additional context**

`npm audit fix` solved the problems, but breaks `npm run storybook`.

**Comment by dyson-yamashita** [comment]
The `npm run storybook` broken problem was resolved by updating below package
```
npm install -D @storybook/react-vite
```

We have also updated the following:
```
npm install -D @storybook/test
npm install -D @storybook/react
npm install -D @storybook/addon-interactions
npm install -D tailwindcss
```


```
pufu-editor % npm audit
found 0 vulnerabilities
```

The above corrections are reflected in the PR https://github.com/goto-lab/pufu-editor/pull/27

**Comment by dyson-yamashita** [comment]
Thank you for raising the issue.
Close this issue by RP #27 .
